# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-03-14 16:16:22
"""
import arcpy
from sys import argv

def Model(Expression="LANDCOVER = 'Bare_Land/Sand'"):  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    birds = "birds"
    Land_cover = "Land_cover"
    total_adults_landcover_Forest_Shrub = "C:\\Users\\Alden Summerville\\MEGASync\\Documents\\AdvGIS\\Assignment1-birds\\Assignment1-birds\\Assignment1-birds.gdb\\total_adults_landcover_Forest_Shrub"

    # Process: Intersect (Intersect) (analysis)
    Output_Feature_Class = "C:\\Users\\Alden Summerville\\MEGASync\\Documents\\AdvGIS\\Assignment1-birds\\Assignment1-birds\\Assignment1-birds.gdb\\birds_Intersect"
    arcpy.analysis.Intersect(in_features=[[birds, ""], [Land_cover, ""]], out_feature_class=Output_Feature_Class, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")

    # Process: Summary Statistics (Summary Statistics) (analysis)
    total_adults = "C:\\Users\\Alden Summerville\\MEGASync\\Documents\\AdvGIS\\Assignment1-birds\\Assignment1-birds\\Assignment1-birds.gdb\\total_adults"
    arcpy.analysis.Statistics(in_table=Output_Feature_Class, out_table=total_adults, statistics_fields=[["ADULTS", "SUM"]], case_field=[])

    # Process: Summary Statistics (2) (Summary Statistics) (analysis)
    adults_by_landcover = "C:\\Users\\Alden Summerville\\MEGASync\\Documents\\AdvGIS\\Assignment1-birds\\Assignment1-birds\\Assignment1-birds.gdb\\adults_by_landcover"
    arcpy.analysis.Statistics(in_table=Output_Feature_Class, out_table=adults_by_landcover, statistics_fields=[["ADULTS", "SUM"]], case_field=["LANDCOVER"])

    # Process: Table Select (Table Select) (analysis)
    total_adults_landcover_select = "C:\\Users\\Alden Summerville\\MEGASync\\Documents\\AdvGIS\\Assignment1-birds\\Assignment1-birds\\Assignment1-birds.gdb\\total_adults_landcover_select"
    arcpy.analysis.TableSelect(in_table=adults_by_landcover, out_table=total_adults_landcover_select, where_clause=Expression)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Alden Summerville\MEGASync\Documents\AdvGIS\Assignment1-birds\Assignment1-birds\Assignment1-birds.gdb", workspace=r"C:\Users\Alden Summerville\MEGASync\Documents\AdvGIS\Assignment1-birds\Assignment1-birds\Assignment1-birds.gdb"):
        Model(*argv[1:])
